"""Stream-to-systolic tile regression against a NumPy reference."""

import os

import cocotb
import numpy as np
from cocotb.clock import Clock
from cocotb.triggers import ReadOnly, RisingEdge, Timer

N = int(os.environ.get("N", "4"))
KMAX = int(os.environ.get("KMAX", "16"))
WPR = N // 4


def pack_word(values):
    word = 0
    for lane, value in enumerate(values):
        word |= (int(value) & 0xFF) << (8 * lane)
    return word


def feed_words(a, b):
    a_words, b_words = [], []
    for k in range(a.shape[1]):
        for w in range(WPR):
            a_words.append(pack_word(a[w * 4 : (w + 1) * 4, k]))
            b_words.append(pack_word(b[k, w * 4 : (w + 1) * 4]))
    return a_words, b_words


async def send_stream(dut, prefix, words):
    valid = getattr(dut, f"{prefix}_stream_valid")
    ready = getattr(dut, f"{prefix}_stream_ready")
    data = getattr(dut, f"{prefix}_stream_data")
    valid.value = 1
    for word in words:
        data.value = word
        while True:
            await RisingEdge(dut.clk)
            if ready.value:
                break
    valid.value = 0


async def reset(dut):
    dut.rst_n.value = 0
    dut.start.value = 0
    dut.k_len.value = 0
    dut.a_stream_valid.value = 0
    dut.b_stream_valid.value = 0
    dut.c_stream_ready.value = 0
    for _ in range(3):
        await RisingEdge(dut.clk)
    dut.rst_n.value = 1
    await RisingEdge(dut.clk)


async def run_case(dut, a, b):
    # Leave the prior case's ReadOnly phase before driving a new descriptor.
    await Timer(1, unit="ns")
    dut.k_len.value = a.shape[1]
    dut.start.value = 1
    await RisingEdge(dut.clk)
    dut.start.value = 0
    dut.c_stream_ready.value = 1
    a_words, b_words = feed_words(a, b)
    a_task = cocotb.start_soon(send_stream(dut, "a", a_words))
    b_task = cocotb.start_soon(send_stream(dut, "b", b_words))

    got = []
    while True:
        await RisingEdge(dut.clk)
        await ReadOnly()
        if dut.c_stream_valid.value and dut.c_stream_ready.value:
            raw = int(dut.c_stream_data.value)
            got.append(raw - (1 << 32) if raw & (1 << 31) else raw)
            if dut.c_stream_last.value:
                break
    await a_task
    await b_task
    want = (a.astype(np.int64) @ b.astype(np.int64)).reshape(-1).tolist()
    assert got == want, f"got {got}, want {want}"
    # done is a registered pulse generated by the final output handshake;
    # observe it on the following clock edge after c_stream_last.
    await RisingEdge(dut.clk)
    await ReadOnly()
    assert dut.done.value == 1


@cocotb.test()
async def test_stream_tile_matches_numpy(dut):
    cocotb.start_soon(Clock(dut.clk, 10, unit="ns").start())
    await reset(dut)
    rng = np.random.default_rng(2026)
    for k in (1, min(3, KMAX), KMAX):
        a = rng.integers(-128, 128, (N, k), dtype=np.int64)
        b = rng.integers(-128, 128, (k, N), dtype=np.int64)
        await run_case(dut, a, b)
