#!/usr/bin/env python3
"""Bake the trained INT8 digits MLP into a C header for the RISC-V firmware.

The network, quantisation and integer post-processing are exactly those of
``ml/train_digits.py`` / ``ml/quantized_mlp.py``. The header also carries the
golden predictions and a golden hidden-layer checksum computed by the Python
integer contract, so the firmware can prove it is bit-exact, not just
"accurate enough".

    python3 soc/gen_model.py --out soc/firmware/model_data.h
"""

from __future__ import annotations

import argparse
import pathlib
import sys
import zlib

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "ml"))

from quantized_mlp import quantize_multiplier, requantize_int32  # noqa: E402
from train_digits import train_quantized  # noqa: E402


def layer_params(layer, x_scale):
    acc_scale = x_scale * layer.weights.scale
    bias = np.rint(layer.bias / acc_scale).astype(np.int64)
    mult, shift = quantize_multiplier(acc_scale / layer.output_scale)
    return bias, mult, shift


def c_array(ctype, name, values, per_line=16):
    flat = [int(v) for v in np.asarray(values).reshape(-1)]
    lines = []
    for i in range(0, len(flat), per_line):
        lines.append("    " + ", ".join(str(v) for v in flat[i:i + per_line]) + ",")
    body = "\n".join(lines)
    return (f"static const {ctype} {name}[{len(flat)}] __attribute__((aligned(16))) = {{\n"
            f"{body}\n}};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(ROOT / "soc" / "firmware" / "model_data.h"))
    ap.add_argument("--seed", type=int, default=2026)
    ap.add_argument("--max-iter", type=int, default=250)
    args = ap.parse_args()

    import warnings
    warnings.filterwarnings("ignore")
    qmlp, xq, y_test, pred_float = train_quantized(args.seed, args.max_iter)

    x = xq.values                                   # [n_test, 64] int8
    w1t = qmlp.hidden.weights.values.T.copy()       # [64, 32]  (K x N, row-major)
    w2t = qmlp.output.weights.values.T.copy()       # [32, 10]
    b1, m1, s1 = layer_params(qmlp.hidden, xq.scale)
    b2, m2, s2 = layer_params(qmlp.output, qmlp.hidden.output_scale)

    # Golden integer contract, written out step by step so it is obvious that
    # the firmware must reproduce each intermediate exactly.
    acc1 = x.astype(np.int64) @ w1t.astype(np.int64)
    hidden = requantize_int32(acc1, b1, m1, s1, relu=True)
    acc2 = hidden.astype(np.int64) @ w2t.astype(np.int64)
    logits = requantize_int32(acc2, b2, m2, s2, relu=False)
    pred = logits.argmax(axis=1)
    assert np.array_equal(pred, qmlp.run_integer_contract(xq)), "contract drift"

    n = x.shape[0]
    hidden_crc = zlib.crc32(hidden.astype(np.int8).tobytes())
    logits_crc = zlib.crc32(logits.astype(np.int8).tobytes())
    acc = float(np.mean(pred == y_test))

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as f:
        f.write("/* Generated by soc/gen_model.py - do not edit.\n")
        f.write(f" * sklearn digits, seed={args.seed}, 64-32-10 INT8 MLP.\n")
        f.write(f" * Golden integer-contract accuracy: {acc:.4f} on {n} held-out images.\n */\n")
        f.write("#ifndef MODEL_DATA_H\n#define MODEL_DATA_H\n#include <stdint.h>\n\n")
        f.write(f"#define N_TEST {n}\n#define N_IN {x.shape[1]}\n")
        f.write(f"#define N_HID {w1t.shape[1]}\n#define N_OUT {w2t.shape[1]}\n\n")
        f.write(f"#define L1_MULT {m1}\n#define L1_SHIFT {s1}\n")
        f.write(f"#define L2_MULT {m2}\n#define L2_SHIFT {s2}\n\n")
        f.write(f"#define GOLDEN_HIDDEN_CRC 0x{hidden_crc:08x}u\n")
        f.write(f"#define GOLDEN_LOGITS_CRC 0x{logits_crc:08x}u\n")
        f.write(f"#define GOLDEN_CORRECT {int(np.sum(pred == y_test))}\n\n")
        f.write(c_array("int8_t", "x_test", x))
        f.write(c_array("int8_t", "w1t", w1t))
        f.write(c_array("int32_t", "b1", b1, 8))
        f.write(c_array("int8_t", "w2t", w2t))
        f.write(c_array("int32_t", "b2", b2, 8))
        f.write(c_array("uint8_t", "labels", y_test))
        f.write(c_array("uint8_t", "golden_pred", pred))
        f.write("\n#endif\n")
    print(f"wrote {out}: {n} images, golden accuracy {acc:.4f}, "
          f"hidden_crc={hidden_crc:08x} logits_crc={logits_crc:08x}")


if __name__ == "__main__":
    main()
